apiVersion: v1
kind: Service
metadata:
  name: kazu-deployment
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: kazu-app
